[config]
schemaVersion = "0.0.1"

[package]
namespace = "MT2"
name = "Stoker"
versionNumber = "0.0.1"
description = "Cheat Manager and Console"
websiteUrl = "https://thunderstore.io"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack-5.4.2100 = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "monstertrain2", ]
[publish.categories]
monstertrain2 = [ "items", "skills", ]


