name: Build

on:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: write

env:
  base_version: '0.1.0'
  mod_namespace: 'MT2'
  mod_name: 'Stoker'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Install Thunderstore
        run: |
          dotnet tool install --global tcli
      - name: Setup NuGet Credentials
        run: |
          dotnet nuget update source monster-train-packages -u USERNAME -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
      - name: Restore Dependencies
        run: dotnet restore
      - name: Setup Directory
        run: mkdir dist
      - name: Build Release
        run: dotnet build -c Release --no-restore --output ./dist
      - name: Build thunderstore package
        run: tcli build
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: thunderstore
          path: ./dist
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
      - name: Publish to Thunderstore
        run: tcli publish --file ${{ env.mod_namespace }}-${{ env.mod_name }}-*.zip --token ${{ secrets.THUNDERSTORE_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
